# Generated by Django 2.0.5 on 2018-05-17 10:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', default='DEVICEDEFAULT', max_length=50)),
                ('is_active', models.BooleanField(db_column='ACTIVE', default=True)),
                ('note', models.TextField(blank=True, db_column='NOTE', max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True, db_column='LAST_MODIFIED')),
                ('modified_by', models.ForeignKey(db_column='MODIFIED_BY', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DEVICE',
                'permissions': (('can_post_devices', 'Can POST Devices'), ('can_edit_devices', 'Can EDIT Devices')),
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE')),
            ],
            options={
                'db_table': 'TENANT',
                'permissions': (('can_post_tenants', 'Can POST Tenants'), ('can_edit_tenants', 'Can EDIT Tenants')),
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('active', models.BooleanField(db_column='ACTIVE', default=True)),
                ('tenant', models.ForeignKey(db_column='TENANT_ID', default='', on_delete=django.db.models.deletion.CASCADE, to='network_config.Tenant')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USER_GROUP',
                'ordering': ['name', 'tenant'],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='owner_group',
            field=models.ForeignKey(db_column='USER_GROUP_ID', on_delete=django.db.models.deletion.CASCADE, to='network_config.UserGroup'),
        ),
        migrations.AddField(
            model_name='device',
            name='tenant',
            field=models.ForeignKey(db_column='TENANT_ID', on_delete=django.db.models.deletion.CASCADE, to='network_config.Tenant'),
        ),
    ]
